---
- name: setup vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import vpc setup variable
      include_vars: vp_setup1

    - name: Import vpc setup variable
      include_vars: output_vars

    - name: create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionSG_out

    - name: creating bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        group_id: "{{ bastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_out

    - name: insert/update "bastionSGid" in vpc-output_vars
      blockinfile:
         path: vpc-output_vars
         backup: yes
         block:
           bastionSGid: {{bastionSG_out.group_id}}








