---
- name: setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import vpc setup variable
      include_vars: vpc-output_vars

    - name: Import vprofile setup variable
      include_vars: vprostacksetup

    - name: create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: create security group for load balancer
      ec2_group:
        name: vproELB-sg
        description: allow port 80 form everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            cidr_ip: "{{MYIP}}"
        register: bastionSG_out

    - name: creating bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "bastion_host"
          Project: vprofile
          Owner: DevOps Team
      exact_count: 1
      count_tag:
         Name: "bastion_host"





